# Jekyll configuration for RecipeBook GitHub Pages
title: "RecipeBook - A Culinary Journey"
description: "A collection of great recipes organized as daily story-driven cooking adventures"
url: "https://mattleibow.github.io"
baseurl: "/RecipeBook"

# Build settings
markdown: kramdown
highlighter: rouge
# theme: minima  # Using custom layouts instead

# Plugins (all supported by GitHub Pages)
# plugins:
#   - jekyll-feed
#   - jekyll-sitemap
#   - jekyll-seo-tag

# Collections for recipes
collections:
  recipes:
    output: true
    permalink: /:path/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "recipes"
    values:
      layout: "recipe"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Exclude files from processing
exclude:
  - README.md
  - .github/
  - .git/
  - .gitignore
  - vendor/
  - Gemfile
  - Gemfile.lock

# Include all markdown files in date folders
include:
  - 2024/